PPF-433-Add E2E for widget integration
cultuurnet/publiq-platform pull request #1133
Opened 2024-05-23 09:09 UTC by vhande

### Added
- E2E for widget integration

---
Ticket: https://jira.uitdatabank.be/browse/PPF-433

2024-05-23 09:18 UTC, simon-debruijn requested changes

2024-05-23 09:18 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/create-widgets-integration.test.ts
> +test("As an integrator I can create a new integration", async ({
```suggestion
test("As an integrator I can create a new widget integration", async ({
```

2024-05-23 09:18 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/create-widgets-integration.test.ts
> +  const newPage = await pagePromise;
why is this page event promise needed?

2024-05-23 09:18 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/create-widgets-integration.test.ts
> +  await newPage.getByRole("button", { name: "Nieuwe widget maken" }).click();
I think this should better be an assertion like
```ts
expect(newPage.getByRole("button", { name: "Nieuwe widget maken" })).toBeVisible()
```

2024-05-23 09:53 UTC, brampauwelyn approved these changes

2024-05-24 07:56 UTC, simon-debruijn approved these changes

2024-05-24 08:05 UTC, merged