Always select first integration type by default
cultuurnet/publiq-platform pull request #1195
Opened 2024-06-11 09:36 UTC by Anahkiasen

### Added

### Changed
- Always select first integration type by default

### Removed

### Fixed

---
Ticket: https://jira.publiq.be/browse/PPF-499

2024-06-11 11:14 UTC, LucWollants approved these changes

2024-06-14 07:37 UTC, simon-debruijn requested changes

2024-06-14 07:37 UTC, simon-debruijn commented on resources/ts/Pages/Integrations/New.tsx
> +    : integrationTypesInfo[0].type;
Is it safe to always take the first element?

2024-07-02 11:57 UTC, brampauwelyn approved these changes

2024-07-08 18:57 UTC, simon2712 approved these changes

2024-07-08 19:01 UTC, simon-debruijn approved these changes

2024-07-09 09:34 UTC, merged