PPF-471-e2e-UiTPAS integration organizer
cultuurnet/publiq-platform pull request #1336
Opened 2024-08-22 14:27 UTC by vhande

### Added
- Add an organizer to an UiTPAS integration
- Remove an organizer from an UiTPAS integration

### Changed
- Request activation

---
Ticket: https://jira.uitdatabank.be/browse/PPF-471

2024-08-23 08:33 UTC, LucWollants approved these changes

2024-08-23 11:41 UTC, simon-debruijn requested changes

2024-08-23 11:41 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/remove-organizer-uitpas-integration.test.ts
> +  await addUiTPASOrganizer(page);
Strange that you are importing a helper from another test. It would be better to add a separate file.

2024-08-23 11:41 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/add-organizer-uitpas-integration.test.ts
> +  await page.getByRole("button", { name: "Bevestigen" }).click();
Since you use this function in multiple places, you can add an assertion here that the action of adding an organizer was succesfull

2024-08-23 11:41 UTC, simon-debruijn commented on e2e/tests/integrations/integrator/request-activation.ts
> +    await page.locator('input[name="organizers"]').click();
I don't think the click is needed before fill

2024-08-23 11:42 UTC, simon-debruijn commented on resources/ts/Components/Integrations/Detail/OrganizersInfo.tsx
> +                    id={organizer.name[i18n.language]}
Maybe add a data-testid instead? Since that is what you can use in playwright by getByTestId

2024-09-02 07:50 UTC, simon-debruijn approved these changes

2024-09-02 12:25 UTC, merged