PPF-167-navigation
cultuurnet/publiq-platform pull request #347
Opened 2023-06-07 13:46 UTC by vhande

### Added
- HeaderMobile
- NavigationElements
- SecondaryButton

Desktop:
![HeaderDesktop](https://github.com/cultuurnet/publiq-platform/assets/78013271/8f7583ff-0dcd-4089-8a27-d7f78f358869)
Mobile:
![HeaderMobile](https://github.com/cultuurnet/publiq-platform/assets/78013271/0d02b5a6-9603-4e9e-8c27-6b9501a585d4)
![HeaderMobileModal](https://github.com/cultuurnet/publiq-platform/assets/78013271/4cd94831-42d7-4f5c-acad-3d79f1f57e29)

---
Ticket: https://jira.uitdatabank.be/browse/...

2023-06-07 14:10 UTC, brampauwelyn commented on resources/ts/Shared/NavigationElements.tsx
> +        {["integrations", "support"].map((pageTitle) => (
Maybe you can define the pages in a `const` above? 
```javascript
const pages = ["integrations", "support"]
```

2023-06-07 14:10 UTC, brampauwelyn commented on resources/ts/Shared/SecondaryButton.tsx
> +export const SecondaryButton = ({ children, className, ...props }: Props) => {
I would prefer to invert the naming (both in the filename as in the variable name).

```suggestion
export const ButtonSecondary = ({ children, className, ...props }: Props) => {
```

2023-06-07 14:10 UTC, brampauwelyn commented on resources/ts/Shared/SecondaryLinkButton.tsx
> +export const SecondaryLinkButton = ({
Same here I prefer to invert the naming. 
So you only need to read the first part of the file to know that it's about a button...

```suggestion
export const ButtonLinkSecondary = ({
```

2023-06-07 14:24 UTC, simon-debruijn requested changes
In mobile when we show the modal/dialog, we should maybe show a darker backdrop behind it. Now the modal doesn't stand out enough compared to the content behind it.

2023-06-08 14:11 UTC, simon-debruijn approved these changes

2023-06-08 14:14 UTC, merged