PPF-186 - Admin can now activate individual auth0 clients
cultuurnet/publiq-platform pull request #475
Opened 2023-08-31 13:40 UTC by grubolsch

### Added
Admin can now activate individual auth0 clients

---
Ticket: https://jira.uitdatabank.be/browse/PPF-186

2023-09-01 11:37 UTC, LucWollants requested changes
Same remark as for the block action. There is a difference between an `Event`, something that happened and was persisted, and a `Command` or `Job` which is the intention to modify.

2023-09-05 10:42 UTC, grubolsch commented
> Same remark as for the block action. There is a difference between an `Event`, something that happened and was persisted, and a `Command` or `Job` which is the intention to modify.

I have updated the PR with your feedback.

2023-09-05 11:00 UTC, LucWollants commented on app/Auth0/Jobs/ClientActivatedListener.php
> +        $this->logger->info(
I think this success message is traced even when the model was not found.

2023-09-05 11:06 UTC, LucWollants commented on app/Auth0/Jobs/ClientActivatedListener.php
> +final class ClientActivatedListener implements ShouldQueue
The name should be `ActivateClientListener`

2023-09-05 12:48 UTC, merged