PPF-187-detail page-contacts
cultuurnet/publiq-platform pull request #533
Opened 2023-10-06 09:44 UTC by vhande

### Added
-ContactsTable
-ContactsTableContent
-ContactsTableDesktop
-ContactsTableMobile

### Changed
-Translations

### Removed
-ContributorTable

### Fixed

---
Ticket: https://jira.uitdatabank.be/browse/PPF-187

2023-10-06 14:23 UTC, simon-debruijn requested changes

2023-10-06 14:23 UTC, simon-debruijn commented on resources/ts/Components/Card.tsx
> +  border,
The props that are optional and boolean like `border` and `badge` better have a explicit false default value

2023-10-06 14:23 UTC, simon-debruijn commented on resources/ts/Components/ContactsTableContent.tsx
> +  ComponentProps<"div">;
```suggestion
import { Contact } from "../Pages/Integrations/Index";

type Props = { desktop?: boolean; mobile?: boolean } & ContactsTableProps &
  ComponentProps<"div">;
```

2023-10-06 14:23 UTC, simon-debruijn commented on resources/ts/Components/ContactsTableContent.tsx
> +  mobile,
You could also use a display prop instead with type `'mobile' | 'desktop'`
But this approach is also perfect 👍🏻

2023-10-06 14:23 UTC, simon-debruijn commented on resources/ts/Components/ContactsTableContent.tsx
> +                (data[type.label as keyof ContactFormData] as Contact)
We can probably search the correct contact in the mapping of contactTypes

Something like this:

```ts
{contactTypes.map((type) => {
    const contact = data[type.label];
    
    return (
        <tr
```

Also you can change
```ts
const contactTypes = [
    { label: "functional", id: functionalId },
    { label: "technical", id: technicalId },
  ];
```

To

```ts
const contactTypes = [
    { label: "functional", id: functionalId },
    { label: "technical", id: technicalId },
  ] as const;
```

You won't need the `as keyof ContactFormData`

2023-10-10 11:28 UTC, brampauwelyn commented
@vhande 
One little design remark.
I would make the border of the whole card less hard. 
Maybe use a lighter grey? Or no border at all with a slight box shadow?

2023-10-11 07:18 UTC, simon-debruijn approved these changes

2023-10-11 07:40 UTC, merged