PPF-188-support slack
cultuurnet/publiq-platform pull request #577
Opened 2023-10-26 12:29 UTC by vhande

### Added
- SupportController
- InformationDialog

---
Ticket: https://jira.uitdatabank.be/browse/PPF-188

2023-10-26 13:52 UTC, simon-debruijn requested changes

2023-10-26 13:52 UTC, simon-debruijn commented on app/Http/Controllers/SupportController.php
> +        $email = Auth::user()?->email;
The `sendInvitation` method should probably be under the authenticated routes. If the user is not authenticated and on the support page and clicks the join slack button we first let them login.

Then we'll be sure that `Auth::user()` is not null

2023-10-26 13:52 UTC, simon-debruijn commented on resources/translations/nl.json
> +    "invite_wrong": "Er is iets fout gegaan. Probeer het later opnieuw."
```suggestion
    "invite_error": "Er is iets fout gegaan. Probeer het later opnieuw."
```
For consistency

2023-10-26 13:52 UTC, simon-debruijn commented on routes/web.php
> +Route::post('/support/slack', [SupportController::class, 'sendInvitation']);
```suggestion
Route::post('/support/slack/invite', [SupportController::class, 'sendSlackInvitation']);
```

2023-10-26 14:38 UTC, vhande commented on resources/ts/Components/SupportCard.tsx
> +  const handleRedirect = () => router.get(translateRoute("/support"));
It doesn't work as we have one more redirect after this.

2023-10-26 15:00 UTC, simon-debruijn requested changes

2023-10-26 15:00 UTC, simon-debruijn commented on app/Http/Controllers/SupportController.php
> +            if (!$response->ok() | $body['ok'] === false) {
```suggestion
            if (!$response->ok() || $body['ok'] === false) {
```

2023-10-30 16:17 UTC, simon-debruijn commented on app/Http/Controllers/SupportController.php
> +                    'emails' => $email,
I now see in the slack docs that emails is supposed to be an array. So even if this works, it is better to follow the correct guidelines.

```suggestion
                    'emails' => [$email],
```

2023-10-30 16:19 UTC, simon-debruijn commented on app/Http/Controllers/SupportController.php
> +            'slackError' => $slackError,
We can also merge these into 1 `slackStatus` which can be `success` or `error`

2023-10-31 19:28 UTC, simon-debruijn approved these changes

2023-11-07 11:04 UTC, merged