Track integration keys distribution
cultuurnet/publiq-platform pull request #719
Opened 2024-01-16 12:17 UTC by Anahkiasen

### Added
- Track integration keys distribution

---
Ticket: https://jira.publiq.be/browse/PPF-258

2024-01-17 13:09 UTC, LucWollants requested changes
I would add some extra unit tests, maybe for the repositories and handlers?

I also noticed that the unit tests are failing, can you verify why?

2024-01-17 14:24 UTC, Anahkiasen commented
@LucWollants Yes should have marked this one as draft, will try to wrap it up today or tomorrow

2024-01-22 14:03 UTC, LucWollants approved these changes

2024-01-23 13:26 UTC, simon-debruijn approved these changes

2024-01-23 16:19 UTC, merged