PPF-367-404 page
cultuurnet/publiq-platform pull request #970
Opened 2024-04-09 12:14 UTC by vhande

### Added
-404 page

![Screenshot ](https://github.com/cultuurnet/publiq-platform/assets/78013271/98fbb069-2493-403f-a802-d6feccbd187d)

---
Ticket: https://jira.uitdatabank.be/browse/PPF-367

2024-04-09 13:15 UTC, simon-debruijn requested changes

2024-04-09 13:15 UTC, simon-debruijn commented on app/Exceptions/Handler.php
> +        return Inertia::render('Error', ['statusCode' => '500']);
```suggestion
        return Inertia::render('Error', ['statusCode' => 500]);
```

the status code can be a number

2024-04-09 13:15 UTC, simon-debruijn commented on resources/ts/Pages/Error.tsx
> +  statusCode: string;
```suggestion
  statusCode: number;
```

2024-04-09 13:15 UTC, simon-debruijn commented on resources/ts/Pages/Error.tsx
> +  if (statusCode === "500")
```suggestion
  if (statusCode === 500)
```

2024-04-09 13:15 UTC, simon-debruijn commented on resources/ts/Pages/Error.tsx
> +  if (statusCode === "500")
Maybe it is more logical to check for 404 and return the jsx. And the default return at the end is a 500 return

2024-04-09 13:15 UTC, simon-debruijn commented on resources/ts/Components/ErrorImage.tsx
> +import Error from "../../images/Error.svg";
```suggestion
import NotFoundError from "../../images/NotFoundError.svg";
```

2024-04-09 13:18 UTC, brampauwelyn approved these changes
BIUTIFUL ⭐

2024-04-10 07:41 UTC, simon-debruijn approved these changes

2024-04-10 07:55 UTC, merged